# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: awscli.spec

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: aws-cli
# downstream (Fedora) RPM package name
downstream_package_name: awscli

actions:
  post-upstream-clone:
  - curl -sLO https://src.fedoraproject.org/rpms/awscli/raw/epel9/f/awscli.spec
  - sed 's/bcond_without  tests/bcond_with tests/g' -i awscli.spec

jobs:
  - job: copr_build
    trigger: pull_request
    packit_instances: ["stg"]
    targets:
      - centos-stream+epel-next-9
  - job: vm_image_build
    trigger: pull_request
    packit_instances: ["stg"]
    image_request:
      architecture: x86_64
      image_type: aws
      upload_request:
        type: aws
        options:
          share_with_accounts: ["727920394381"]
    image_customizations:
      packages: [awscli]
      payload_repositories:
      - rhsm: false
        baseurl: https://kojipkgs.fedoraproject.org/repos/epel9-build/latest/x86_64/
        check_gpg: false
    image_distribution: rhel-90
    owner: packit-stg
    project: TomasTomecek-aws-cli-1
    copr_chroot: centos-stream+epel-next-9-x86_64

